rpi: False                     # Enable optimizations for the RPi
line_in: False                 # Enable a second audio input

device_1_id: 1                 # The device ID for the primary input
device_2_id: 2                 # The device ID for the secondary inpuy [opt.]

channels: 1                    # The number of channels the device has
format: 8                      # The audio format for the input devices [int16]
chunk: 1024                    # The amount of data to request per loop
rate: 44100                    # The sampling rate of the device

quiet_music: 15                # The lower threshold for music
loud_music: 3                  # The upper threshold for music

quiet_speech: 30               # The lower threshold for speech
loud_speech: 12                # The upper threshold for speech

screen_height: 240             # The default display height
screen_width: 320              # The default display width

average_samples: 20            # The number of samples to average for
graph_samples: 200             # The number of samples to show on the graph

split_frequency: 125           # The frequency to split at in split mode

round_cornders: True            # Should the corners of panels be rounded

graph_colour_2: [130, 60, 70]  # The secondary colour on the graph
border_colour: [15, 15, 15]    # The borders between panels
border_light: [90, 95, 100]    # A lighter border shade
graph_colour: [60, 130, 70]    # The primary colour on the graph
text_colour: [80, 100, 120]    # The colour of foreground text
message_fg: [230, 230, 230]    # The foreground colour for message boxes
bg_colour: [60, 80, 110]       # The background colour
bg_darker: [50, 60, 90]        # A darkened background
fg_colour: [0, 0, 0]           # The colour of text on panels

light_blue: [80, 180, 220]     # The colour of the "VU" bars
dark_blue: [10, 35, 60]        # The colour of the "VU" bars' background
orange: [230, 190, 45]         # The colour for when the audio is too quiet
green: [50, 150, 80]           # The colour for when the audio is okay
red: [215, 45, 50]             # The colour for when the audio is too loud

source_1_label: 'MIC'          # The label for the primary source
source_2_label: 'OUT'          # The label for the secondary source

s1_split_label: 'HIGH'         # The label for the highpass in split mode
s2_split_label: 'LOW'          # The label for the lowpass in split mode

button_colour: [               # The colour palette for an unusable button
    [64 , 87 , 54 ],
    [129, 146, 114],
    [43 , 55 , 31 ],
    [51 , 64 , 38 ]
]
button_dgrey_colour: [         # The colour palette for a disabled button
    [66 , 67 , 65 ],
    [81 , 81 , 82 ],
    [45 , 45 , 45 ],
    [43 , 43 , 43 ]
]
button_grey_colour: [          # The colour palette for an inactive button
    [132, 134, 131],
    [162, 163, 165],
    [91 , 91 , 91 ],
    [87 , 87 , 87 ]
]
button_blue_colour: [          # The colour palette for an active button
    [117, 206, 240],
    [140, 231, 255],
    [28 , 109, 139],
    [72 , 168, 208]
]

big_font_size: 20              # The font size for buttons and panel labels
font_size: 10                  # The font size for the "UV" meter labels

fps: 30                        # The FPS to refresh the display at

colour_padding: 4              # The internal padding around coloured regions
padding: 0.5                   # The padding between panes

watermark: True                # Toggle the mark in the bottom right
